import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/core-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/gateway',
        'architecture/brain-and-hands',
        'architecture/memory-system',
        'architecture/heartbeat',
      ],
    },
    {
      type: 'category',
      label: 'First 7 Days',
      collapsed: true,
      items: [
        'guides/first-7-days/index',
        'guides/first-7-days/day-1-make-it-yours',
        'guides/first-7-days/day-2-daily-driver',
        'guides/first-7-days/day-3-automation',
        'guides/first-7-days/day-4-skills',
        'guides/first-7-days/day-5-multi-channel',
        'guides/first-7-days/day-6-power-moves',
        'guides/first-7-days/day-7-production',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/basic-usage',
        'guides/channels',
        'guides/custom-channels',
        'guides/soul-md',
        'guides/skill-development',
        'guides/skill-workshop',
        'guides/heartbeat',
        'guides/mcp-servers',
        'guides/model-selection',
        'guides/local-models',
        'guides/cloud-gpu-models',
        'guides/cost-management',
        'guides/clawhub',
        'guides/multi-agent',
        'guides/workboard',
        'guides/plugin-system',
        'guides/memory-systems',
        'guides/automation',
        'guides/webclaw',
        'guides/cicd-testing',
        'guides/monitoring',
        'guides/deployment-options',
        'guides/hosting-providers',
        'guides/lightweight-variants',
        'guides/privacy-compliance',
        'guides/use-cases',
        'guides/migration',
        {
          type: 'category',
          label: 'Recipes',
          collapsed: true,
          items: [
            'guides/recipes/email-assistant',
            'guides/recipes/code-reviewer',
            'guides/recipes/smart-home',
            'guides/recipes/research-agent',
            'guides/recipes/advanced-recipes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/overview',
        'security/hardening',
        'security/known-vulnerabilities',
        'security/skill-verification',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/cli',
        'reference/configuration',
        'reference/gateway-api',
        'reference/environment-variables',
        'reference/troubleshooting',
        'reference/faq',
        'reference/ecosystem',
        'reference/comparison',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        'contributing/docs',
        'contributing/openclaw',
      ],
    },
  ],
};

export default sidebars;
